// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { DocumentTypeDTO } from '@app/model/bw/co/roguesystems/fsrfp/document/type/document-type-dto';
import { RegulatedOperationProcessDTO } from '@app/model/bw/co/roguesystems/fsrfp/operation/process/regulated-operation-process-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root',
})
export class RegulatedOperationProcessApi {
  protected path = '/operation/process';

  private http = inject(HttpClient);

  public findById(id: string | any): Observable<RegulatedOperationProcessDTO | any> {
    return this.http.get<RegulatedOperationProcessDTO | any>(`${this.path}/${id}`);
  }

  public getAll(): Observable<DocumentTypeDTO[] | any[]> {
    return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(
    pageNumber: number | any,
    pageSize: number | any,
  ): Observable<Page<RegulatedOperationProcessDTO> | any> {
    return this.http.get<Page<RegulatedOperationProcessDTO> | any>(
      `${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`,
    );
  }

  public remove(id: string | any): Observable<boolean | any> {
    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(process: RegulatedOperationProcessDTO | any): Observable<RegulatedOperationProcessDTO | any> {
    return this.http.post<RegulatedOperationProcessDTO | any>(`${this.path}`, process);
  }

  public search(criteria: string | any): Observable<DocumentTypeDTO[] | any[]> {
    return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
  }

  public findByRegulatedOperation(operationId: string | any): Observable<RegulatedOperationProcessDTO[] | any[]> {
    return this.http.get<RegulatedOperationProcessDTO[] | any[]>(`${this.path}/by-operation/${operationId}`);
  }
}
