// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { RegulatorDTO } from '@app/model/bw/co/roguesystems/fsrfp/regulator/regulator-dto';
import { DocumentTypeDTO } from '@app/model/bw/co/roguesystems/fsrfp/document/type/document-type-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root',
})
export class RegulatorApi {
  protected path = '/regulator';

  private http = inject(HttpClient);

  public findById(id: string | any): Observable<RegulatorDTO | any> {
    return this.http.get<RegulatorDTO | any>(`${this.path}/${id}`);
  }

  public getAll(): Observable<DocumentTypeDTO[] | any[]> {
    return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(pageNumber: number | any, pageSize: number | any): Observable<Page<RegulatorDTO> | any> {
    return this.http.get<Page<RegulatorDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public remove(id: string | any): Observable<boolean | any> {
    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(regulator: RegulatorDTO | any): Observable<RegulatorDTO | any> {
    return this.http.post<RegulatorDTO | any>(`${this.path}`, regulator);
  }

  public search(criteria: string | any): Observable<DocumentTypeDTO[] | any[]> {
    return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
  }
}
